### ISSUE TITLE
加入了tailwind編譯很慢如何解決？

### ISSUE THREAD

**Issue by yudan215** [xlzy520/uniapp-tailwind-uview-starter#1]
加入了tailwind編譯很慢如何解決？

**Comment by xlzy520** [comment]
可以更新一下
我现在把[postcss 里的purge](https://github.com/xlzy520/uniapp-tailwind-uview-starter/blob/ce8294cd9fe20bff6d1f4045d5ebf01c43ab136b/postcss.config.js#L20)注释掉了

**Comment by xlzy520** [comment]
我当时加这个是为了清除uview没有使用到的css，这个可以在生产环境下开启

**Comment by yudan215** [comment]
刚试过关闭了会报
`  46040 | 
  46041 | @media (min-width: 1536px) {
> 46042 |   .\32xl--container {
        |   ^
  46043 |     width: 100%
  46044 |   }
  46045 | `

**Comment by xlzy520** [comment]
贴一下你的postcss

**Comment by yudan215** [comment]
`const path = require('path')
const purgecss = require('postcss-purgecss')

module.exports = {
  syntax: 'postcss-scss',
  parser: require('postcss-comment'),
  plugins: [
    require('postcss-import')({
      resolve (id) {
        if (id.startsWith('~@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
        } else if (id.startsWith('@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
        } else if (id.startsWith('/') && !id.startsWith('//')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
        }
        return id
      }
    }),
    require('tailwindcss')({ config: './tailwind.config.js' }),
    require('@dcloudio/vue-cli-plugin-uni/packages/postcss'),
    purgecss({
      content: ['./**/*.vue', './**/*.wxml', './**/*.html'],
      css: ['**/*.wxss', '**/*.css'],
    }),
    require('autoprefixer')({
      remove: process.env.UNI_PLATFORM !== 'h5'
    }),
    require('postcss-class-rename')({
      '\\\\:': '--',
      '\\\\/': '_',
    }),
  ]
}
`

**Comment by xlzy520** [comment]
> 刚试过关闭了会报
> ` 46040 |
> 46041 | @media (min-width: 1536px) {
> 
> > 46042 |   .\32xl--container {
> > |   ^
> > 46043 |     width: 100%
> > 46044 |   }
> > 46045 | `

我现在这个postcss和tailwindcss mp-weixin配置更新了， 你可以重新拉一下项目更新一下这两个文件

**Comment by xlzy520** [comment]
```js
const path = require('path')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  syntax: 'postcss-scss',
  parser: require('postcss-comment'),
  plugins: [
    require('postcss-import')({
      resolve(id, basedir, importOptions) {
        if (id.startsWith('~@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
        } else if (id.startsWith('@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
        } else if (id.startsWith('/') && !id.startsWith('//')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
        }
        return id
      },
    }),
    // purgecss({
    //   content: ['./**/*.vue', './**/*.wxml', './**/*.html'],
    //   css: ['**/*.wxss', '**/*.css'],
    // }),
    require('autoprefixer')({
      remove: process.env.UNI_PLATFORM !== 'h5',
    }),
    require('@dcloudio/vue-cli-plugin-uni/packages/postcss'),
    require('tailwindcss')({ config: './tailwind.config.js' }),
    require('postcss-class-rename')({
      '\\\\:': '--',
      '\\\\/': '_',
    })
  ],
}

```

**Comment by yudan215** [comment]
对比了下好像没差别啊

**Comment by xlzy520** [comment]
```js
purgecss({
content: ['.//*.vue', './/.wxml', './**/.html'],
css: ['/*.wxss', '/*.css'],
}),
```
你这里没有注释掉呀

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/116682747-3cef8d00-a9e1-11eb-8f00-71a2cfd265c9.png)

**Comment by yudan215** [comment]
我就是说注释了这里就报那个错误了

**Comment by yudan215** [comment]
![image](https://user-images.githubusercontent.com/26323005/116682925-7c1dde00-a9e1-11eb-9a81-c4dea642d59e.png)

**Comment by xlzy520** [comment]
不会的，我项目一直都是正常启动的，你可以重启一下项目

**Comment by xlzy520** [comment]
> 不会的，我项目一直都是正常启动的，你可以重启一下项目

因为你还有媒体查询吧，tailwindcss配置我也更新了

**Comment by xlzy520** [comment]
你把这个项目再拉一遍跑一次看看？

**Comment by yudan215** [comment]
估计是我改了tailwind的配置

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/116683159-cc953b80-a9e1-11eb-8899-5f2af4d71f14.png)

**Comment by yudan215** [comment]
`const isH5 = process.env.UNI_PLATFORM === 'h5'

module.exports = {
  purge: {
    content: ['./src/**/*.vue', './src/**/*.wxml'],
  },
  darkMode: 'class', // or 'media' or 'class'
  // corePlugins: {
  //   space: false,
  //   divideWidth: false,
  //   divideColor: false,
  //   divideStyle: false,
  //   divideOpacity: false,
  // },
  corePlugins: [
    isH5 ? 'preflight' : 'container',
    'alignContent',
    'alignItems',
    'backgroundColor',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'borderColor',
    'borderRadius',
    'borderStyle',
    'borderWidth',
    'boxSizing',
    'clear',
    'display',
    'fill',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'fontSize',
    'fontWeight',
    'height',
    'inset',
    'justifyItems',
    'justifyContent',
    'lineHeight',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'objectFit',
    'objectPosition',
    'opacity',
    'overflow',
    'position',
    'padding',
    'placeholderColor',
    'placeholderOpacity',
    'rotate',
    'scale',
    'tableLayout',
    'textAlign',
    'textColor',
    'textDecoration',
    'textOverflow',
    'textTransform',
    'transform',
    'transformOrigin',
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
    'translate',
    'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'wordBreak',
    'zIndex'
  ],
  // variants: {
  //   accessibility: [],
  //   alignContent: [],
  //   alignItems: [],
  //   alignSelf: [],
  //   appearance: [],
  //   backgroundAttachment: [],
  //   backgroundColor: ['dark', 'active', 'disabled'],
  //   backgroundPosition: [],
  //   backgroundRepeat: [],
  //   backgroundSize: [],
  //   borderCollapse: [],
  //   borderColor: [],
  //   borderRadius: [],
  //   borderStyle: [],
  //   borderWidth: [],
  //   boxShadow: [],
  //   cursor: [],
  //   display: [],
  //   fill: [],
  //   flex: [],
  //   flexDirection: [],
  //   flexGrow: [],
  //   flexShrink: [],
  //   flexWrap: [],
  //   float: [],
  //   fontFamily: [],
  //   fontSize: [],
  //   fontSmoothing: [],
  //   fontStyle: [],
  //   fontWeight: [],
  //   height: [],
  //   inset: [],
  //   justifyContent: [],
  //   letterSpacing: [],
  //   lineHeight: [],
  //   listStylePosition: [],
  //   listStyleType: [],
  //   margin: [],
  //   maxHeight: [],
  //   maxWidth: [],
  //   minHeight: [],
  //   minWidth: [],
  //   objectFit: [],
  //   objectPosition: [],
  //   opacity: ['disabled'],
  //   order: [],
  //   outline: [],
  //   overflow: [],
  //   padding: [],
  //   placeholderColor: [],
  //   pointerEvents: [],
  //   position: [],
  //   resize: [],
  //   stroke: [],
  //   tableLayout: [],
  //   textAlign: [],
  //   textColor: ['dark', 'active'],
  //   textDecoration: [],
  //   textTransform: [],
  //   userSelect: [],
  //   verticalAlign: [],
  //   visibility: [],
  //   whitespace: [],
  //   width: [],
  //   wordBreak: [],
  //   zIndex: [],
  // },
  theme: {
    spacing: {
      full: '100%',
      1: '4rpx',
      2: '8rpx',
      '5px': '5rpx',
      '6px': '6rpx',
      '10px': '10rpx',
      '14px': '14rpx',
      '15px': '15rpx',
      '18px': '18rpx',
      4: '16rpx',
      5: '20rpx',
      6: '24rpx',
      7: '28rpx',
      '30px': '30rpx',
      10: '40rpx',
      11: '44rpx',
      12: '48rpx',
      '70px': '70rpx',
      19: '76rpx',
      20: '80rpx',
    },
    borderRadius: {
      full: '100%',
      '2px': '2rpx',
      '3px': '3rpx',
      '5px': '5rpx',
      '35px': '35rpx',
    },
    borderWidth: {
      DEFAULT: '1px',
      2: '2px',
      b: ''
    },
    colors: {
      white: '#ffffff',
      primary: '#00BD92',
      orange: '#FF5102',
      'light-gray': '#F6F6F6',
      gray: '#888888',
      border: '#e6e6e6',
    },
    fontSize: {
      xs: '20rpx',
      sm: ['24rpx', { lineHeight: '33rpx' }],
      base: ['28rpx', { lineHeight: '40rpx' }],
      lg: ['32rpx', { lineHeight: '40rpx' }],
    },
  //   minHeight: {
  //     0: '0upx',
  //     full: '100%',
  //     screen: '100vh',
  //   },
  //   outline: {
  //     none: ['4upx solid transparent', '4upx'],
  //     white: ['4upx dotted white', '4upx'],
  //     black: ['4upx dotted black', '4upx'],
  //   },
  //   extend: {},
  },
  plugins: [],
}
`

**Comment by xlzy520** [comment]
都不对，是这里的问题
![image](https://user-images.githubusercontent.com/28336270/116683341-05351500-a9e2-11eb-823a-fdd2c49b7c33.png)

**Comment by xlzy520** [comment]
你再对比一下，这是我的
![image](https://user-images.githubusercontent.com/28336270/116683375-14b45e00-a9e2-11eb-94ba-f243cd585244.png)

**Comment by xlzy520** [comment]
\\\\四个哦

**Comment by yudan215** [comment]
是四个·github转义了·我用你的tailwind就不会报错

**Comment by yudan215** [comment]
不知道是哪里的配置影响了

**Comment by xlzy520** [comment]
可以把你的项目让我跑一下看看

**Comment by yudan215** [comment]
screens: false,  找到了·我没这个

**Comment by xlzy520** [comment]
我上面都截图这个。
![image](https://user-images.githubusercontent.com/28336270/116684204-424dd700-a9e3-11eb-9e8a-d49171813dde.png)
