### ISSUE TITLE
tailwind最常用的w-full都用不了吗

### ISSUE THREAD

**Issue by q8462880** [xlzy520/uniapp-tailwind-uview-starter#10]

**Comment by q8462880** [comment]
需要重新编译才有效果

**Comment by xlzy520** [comment]
有类似的issue，但是我本地尝试了webstorm和Hbuilder，都是不需要重新编译就有效果的。
你试试第一次改动的时候，手动点击编译，后面修改代码之后保存一下，然后看是否会自动编译。

**Comment by xlzy520** [comment]
@q8462880 小程序、H5均已修复，原因是tailwindcss 3.x版本不能识别2.x版本的content配置的路径
