### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by shelli-site** [xlzy520/uniapp-tailwind-uview-starter#2]
能不能帮我看下这个问题，命令行里是正常的，但webstorm一直报错。
```
D:\Programs\nodejs\node.exe D:\Programs\nvm\npm\node_modules\yarn\bin\yarn.js run dev:mp-weixin
yarn run v1.22.5
$ cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch
请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
小程序各家浏览器内核及自定义组件实现机制存在差异，可能存在样式布局兼容问题，参考：https://uniapp.dcloud.io/matter?id=mp

|  开始编译当前项目至 mp-weixin 平台...postcss-class-rename: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
 ERROR  Error: EINVAL: invalid argument, mkdir 'D:\Works\uni\uniapp-tailwind-uview-starter\dist\dev\mp-weixin\D:\Works\uni\uniapp-tailwind-uview-starter\src\components\divider'
Error: EINVAL: invalid argument, mkdir 'D:\Works\uni\uniapp-tailwind-uview-starter\dist\dev\mp-weixin\D:\Works\uni\uniapp-tailwind-uview-starter\src\components\divider'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

node版本是12.19.0，

感觉是打包的时候出现建错文件了，但命令行是正常的，只有在webstorm上用npm插件运行时会有这个问题。
感谢。

**Comment by xlzy520** [comment]
看起来这个问题和我的项目关系不大，是nodejs的配置问题，我自己也是用webstorm的npm插件启动的，你可以尝试查下相关报错解决一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xlzy520/uniapp-tailwind-uview-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午12:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xlzy520/uniapp-tailwind-uview-starter] 编译错误 (#2)





 
能不能帮我看下这个问题，命令行里是正常的，但webstorm一直报错。
 D:\Programs\nodejs\node.exe D:\Programs\nvm\npm\node_modules\yarn\bin\yarn.js run dev:mp-weixin yarn run v1.22.5 $ cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布 小程序各家浏览器内核及自定义组件实现机制存在差异，可能存在样式布局兼容问题，参考：https://uniapp.dcloud.io/matter?id=mp |  开始编译当前项目至 mp-weixin 平台...postcss-class-rename: postcss.plugin was deprecated. Migration guide: https://evilmartians.com/chronicles/postcss-8-plugin-migration  ERROR  Error: EINVAL: invalid argument, mkdir 'D:\Works\uni\uniapp-tailwind-uview-starter\dist\dev\mp-weixin\D:\Works\uni\uniapp-tailwind-uview-starter\src\components\divider' Error: EINVAL: invalid argument, mkdir 'D:\Works\uni\uniapp-tailwind-uview-starter\dist\dev\mp-weixin\D:\Works\uni\uniapp-tailwind-uview-starter\src\components\divider' error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.  
node版本是12.19.0，
 
感觉是打包的时候出现建错文件了，但命令行是正常的，只有在webstorm上用npm插件运行时会有这个问题。
 感谢。
