### ISSUE TITLE
运行报错，暂时看不出啥问题

### ISSUE THREAD

**Issue by hhdebb** [xlzy520/uniapp-tailwind-uview-starter#7]
#### 环境
- 系统：Win11
- Node：v14.18.0
- Npm：6.14.5
- IDE: WebStorm 2021.3.2
#### 问题
- 拉取到本地未做任何修改 
```shell
// 安装依赖
cnpm install

// 运行
npm run serve
```
- 报错截图
![image](https://user-images.githubusercontent.com/72241812/156707226-e2d262f9-5536-48ea-8127-2c010e362c17.png)

**Comment by xlzy520** [comment]
@hhdebb 未复现，如果可以的话，我可以远程看看

**Comment by hhdebb** [comment]
@xlzy520 上午测试了下，问题出在用cnpm i, 后来我换成npm i就没问题了，估计cnpm下载的包不兼容还是咋的。
